[DOPS-2632] Add a command to install tini in alpine image
soramitsu/gradle-sora-plugin pull request #31
Opened 2023-07-27 11:01 UTC by baotn166

# Task
[DOPS-2628](https://soramitsu.atlassian.net/browse/DOPS-2632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) Add a command to install tini in alpine image

# Description
- Add a command to install tini in alpine image

# Author

2023-07-27 11:16 UTC, marat-biriushev approved these changes

2023-07-28 06:08 UTC, wpi86 requested changes

2023-07-28 06:08 UTC, wpi86 commented on src/main/groovy/jp/co/soramitsu/devops/docker/DockerPlugin.groovy
> +            t.addFile "https://github.com/krallin/tini/releases/download/v0.19.0/tini", "/sbin/tini"
Move tini install to if condition

2023-07-31 09:00 UTC, Mingela approved these changes

2023-07-31 09:07 UTC, baotn166 commented on src/main/groovy/jp/co/soramitsu/devops/docker/DockerPlugin.groovy
> +            t.addFile "https://github.com/krallin/tini/releases/download/v0.19.0/tini", "/sbin/tini"
fixed

2023-07-31 09:25 UTC, marat-biriushev approved these changes

2023-07-31 09:25 UTC, wpi86 approved these changes

2023-07-31 10:23 UTC, Cre-eD approved these changes

2023-07-31 10:25 UTC, merged